### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vaaski** [kbtortur/fastpaint#1]
## MVP #1
- [x] paste image from clipboard
- [x] upload using file input
- [ ] move input to canvas
- [ ] get image from canvas to output
- [ ] copy output to clipboard
- [ ] crop
- [ ] drag n drop images
- [ ] download output to file
- [ ] deploy to netlify

## MVP #2
- [ ] drawing
- [ ] streching
- [ ] styling
- [ ] branding (icons etc)
- [ ] export in specific/multiple sizes
